apiVersion: apps/v1
kind: Deployment
metadata:
  name: auditchecklist-service-deployment
  labels:
    app: AuditChecklistModule
spec:
  replicas: 1
  selector:
    matchLabels:
      app: AuditChecklistModule
  template:
    metadata:
      labels:
        app: AuditChecklistModule
    spec:
      containers:
      - name: checklistcontainerinst
        image: auditmanagementcreg.azurecr.io/checklistcontainer:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: authsvcsecret
---
apiVersion: v1
kind: Service
metadata:
  name: auditchecklistservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: AuditChecklistModule
